# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    ports:
    - 10010:10010
    env:
      VERACODE_API_KEY_ID: $(veracode_api_key_id)
      VERACODE_API_KEY_SECRET: $(veracode_api_key_secret)

services:
  iast_agent_server: iast_agent_server

steps:
  - task: Bash@3
    displayName: 'Before Script'
    inputs:
      targetType: 'inline'
      script: |
        status_code='curl --write-out "%{http_code}" --silent --output /dev/null --insecure $(AGENT_SERVER_URL)'
        echo http_code: $status_code
        export BUILD_TAG='$(Build.BuildNumber)'
        echo Using BUILD_TAG: $BUILD_TAG

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '8.x'
    
  - task: Npm@1
    displayName: 'Build'
    inputs:
      command: 'install'
    
  - task: Npm@1
    displayName: 'Test'
    inputs:
      command: 'custom'
      customCommand: 'test'